### ISSUE TITLE
Docker file for server version 8?

### ISSUE THREAD

**Issue by michielbdejong** [haiwen/seafile-docker#236]
Hi!

I'm trying to test Seafile's open cloud mesh functionality (between Seafile servers) which is implemented in server version 8. Is there a Docker image I can use? Can I just use the Docker image for version 7 as a base, and then update it to use Seafile version 8?

**Comment by ggogel** [comment]
I've created one my own: https://github.com/ggogel/seafile-docker/tree/8.0/image/seafile_8.0
I've only tested a fresh installation so far and it worked. I'd not recommend deploying this on production, as it's completely untested yet.

**Comment by ggogel** [comment]
I've deployed my image over a former 7.1 instance now and it worked.

**Comment by ggogel** [comment]
Checkout my entirely redesigned docker deployment: https://github.com/ggogel/seafile-containerized

**Comment by henry-nicolas** [comment]
@ggogel thanks for providing an alternative image, some suggestions if I may :)
1. It seems we can't create issues on the forked repo ?
2. How feasible would it be to add postgresql support ? 
    I understand upstream doesn't, from what I'v read this mostly relates to lack of migration script between releases.
3. You have quite an exhaustive documentation (README file) which is great. If you add postgres support at some point, kindly also consider documenting migration steps.

**Comment by ggogel** [comment]
1. Thanks for the hint. I've now enabled issues.
2. From what I understand you can use PostgreSQL with Seafile, though it's still in beta and not recommended for production use:
https://github.com/haiwen/seafile-docs/blob/master/deploy/using_postgresql.md
Theoretically it should be possible to integrate this into my deployment, though it would require quite a bit of work and there are other things I've still got on my list, like configurable cronjob for offline garbage collection. I think implementing postgres support would also be easier once Seafile actually fully supports it.

May I ask what's your reason for wanting to use postgres instead of mariadb?

**Comment by henry-nicolas** [comment]
> May I ask what's your reason for wanting to use postgres instead of mariadb?

Sure - basically most of the existing setup I have here was already running postgres, so I had to introduce MariaDB for seafile. I run MariaDB inside a container, but there is still some management overhead to properly handle backup, monitoring, 2RDBMS running so that is a bit less optimal ressources wide.

Eventually, nothing against MariaDB, it's just about avoiding the extra work :-)

Thanks for your reply.

**Comment by ggogel** [comment]
Ok, that's an comprehensible reason.

I'll definitely look into it once Seafile fully supports it and if more users are requesting it.

**Comment by deadash** [comment]
@ggogel Is postgresql supported now?
