### ISSUE TITLE
The avatar icon does not display properly

### ISSUE THREAD

**Issue by ITBOX-ITBOY** [haiwen/seafile-docker#239]
<img width="803" alt="test" src="https://user-images.githubusercontent.com/15922437/102865710-218fd680-4471-11eb-9e20-0e7ff0b4e272.png">

**Comment by patrick-birkle** [comment]
Hello,

is your seafile running behind a reverse-proxy? If yes you maybe have to edit the 'SERVICE_URL' and 'FILE_SERVER_ROOT' in your administration ui. 

I'm running seafile behind a nginx reverse-proxy (ssl termination) and therefore the installation is running on plain http, but is still https encrypted through reverse-proxy. Both of the urls are therefore pointed to the http:// url instead of the https:// ones without ports (in my case, because I only opened https port 443). This is my current configuration:

![image](https://user-images.githubusercontent.com/47027239/102879194-b2eb5280-4449-11eb-87a6-e2bb1238fa66.png)
