### ISSUE TITLE
Custom data directory

### ISSUE THREAD

**Issue by moritzschaefer** [haiwen/seafile-docker#3]
I would like to choose a mountpoint (/media/harddrivexyz) for the seafile data directory (currently in shared/seafile). Unfortunately a simple symlink inside shared doesn't work, as the seafile-container won't find the target of the symlink. 
Is the best solution to update the launcher file and set custom paths in there to achieve custom data-directories?

**Comment by lins05** [comment]
>Is the best solution to update the launcher file and set custom paths in there to achieve custom data-directories?

That sounds doable. But there are some simpler solutions:

- You can bind mount `/media/harddrivexyz/seafile` to `/path/to/shared/seafile`
- Or you can clone seafile-docker to `/media/harddrivexyz/` from the beginning.

**Comment by simonsan** [comment]
I'm working at a migration from a normal seafile installation to a docker container. Can anyone help there, started a new page in the wiki. Struggling myself, as the docker container won't start up properly.

https://github.com/haiwen/seafile-docker/wiki/HowTo:-Migrate-from-a-normal-Seafile-installation-to-a-docker-container

Thank you

**Comment by joergweber** [comment]
@lins05 Could you please provide an example how to bind mount the `shared/seafile` folder in Docker (Windows) to a custom path? I am trying to achieve the same as at @moritzschaefer, but I am really struggling.

I want to migrate from Seafile for Windows to Docker. Seafile-server and DB are installed on an SSD, the large seafile-data folders etc. are on a pooled drive storage. I do not how to achieve this with Seafile Docker for Windows.

**Comment by moritzschaefer** [comment]
@joergweber I just set 
`sharedir=/media/data/seafile-shared`

in ./launcher

**Comment by joergweber** [comment]
@moritzschaefer I've tried that before, but I must be doing something wrong:

Just to be clear: 
- I have v6.2.3 in Docker under Windows. 
- Seafile is installed in `C:\seafile-docker` and I am trying to move the folder C:\seafile-docker\shared to another outside path, e.g. `C:\seafile-shared`

On a fresh install, I have in `launcher.ps1` modified `$sharedir = "$dockerdir/shared"` to `/seafile-shared`. I've then done `bootstrap and  `start`. The folder `C:\seafile-shared` gets correctly created, with some files and folders in it, but I receive the error message `Cannot find path 'C:\seafile-shared\seafile\seafile-data\current_version' because it does not exist`

Do you have any idea what I am doing wrong?

**Comment by moritzschaefer** [comment]
Can't help with windows. Sorry

**Comment by shoeper** [comment]
Closing because setting a data directory is possible (bind mount or using a docker volume).
