### ISSUE TITLE
why not docker-compose？

### ISSUE THREAD

**Issue by gumutianqi** [haiwen/seafile-docker#36]
why not use docker-compose？

**Comment by xiayhub** [comment]
+1.

I find it disturbing having to deal with the launch script:
1. Why bootstrapping is required?  Could not the container self-bootstrap upon first run?  If it is just for letsencrypt integration it could have been a auxiliary script instead of a mandated one.

2. An extra layer to deal with.  It seems fine IF everything just always works.  However, in reality NOTHING just always works.  Whenever anything went wrong this script adds a pile of code to look into.  This is unnecessary trouble from not starting docker container through standard docker workflow.

3. Loss of control.  The wrapper script took away a ton of control over the details of underlying docker container, e.g. how network is setup, how ports and path are mapped, etc.

I am not saying that the launcher script should be thrown away.  I am just saying that HAVING TO deal with this kind of wrapper script isn't everyone's favorite.  It would probably help a lot of people if there is documentation of a canonical docker way to start the container like [gitlab](https://docs.gitlab.com/omnibus/docker/README.html) do.  It doesn't takes much more steps to step up the container but do expose much more information on how the container works so people would know how to tailor the container setup to suit their need & environment.

**Comment by rcludwick** [comment]
So this was so painful to get started that after spending an hour trying to get something to work I went looking somewhere else.

**Comment by Dehalion** [comment]
@rcludwick Did you find a better way to deploy Seafile in a docker container?

**Comment by rcludwick** [comment]
Yes.  I went with foxel/seafile-docker.

My docker-compose.override looks like this:

`version: '2'

services:
  seafile:
    restart: always
    ports:
      - 8888:8888
    environment:
      - SEAFILE_URL=https://your.external.hostname.com
      - VIRTUAL_HOST=your.external.hostname.com
      - VIRTUAL_PORT=8888
      - LETSENCRYPT_HOST=your.external.hostname.com
      - LETSENCRYPT_EMAIL=your-email@gmail.com
    volumes:
      - /your/storage/path/to/seafile:/seafile
    networks:
      - default
      - nginxgen_proxy

  mysql:
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=
      - MYSQL_ROOT_PASSWORD=YOUR_MYSQL_RANDOM_PASSWORD
    volumes:
      - /your/storage/path/to/seafile-db/mysql:/var/lib/mysql
    networks:
      - default

# Optional ddclient config
  ddclient:
    restart: always
    volumes:
      - ./ddclient/config:/config
    environment:
      - PGID=1000
      - PUID=1000
    networks:
      - default

networks:

  nginxgen_proxy:
    external: true
`

**Comment by rcludwick** [comment]
@Dehalion:

Boy that brought back bad memories.

So foxel/seafile-docker is good, the only problem is that I wanted to host multiple docker instances behind a single nginx client as well as TLS, so the default config didn't really work out for me.

If you want the setup I have, with nginx-gen and letsencrypt, then you're going to need to do the instructions that follow. In the end there are two nginx's running.  One for nginx_gen to handle the hostname/TLS proxy and one inside foxel/seafile-docker to map /seafhttp to port 8082.  

If that's too much for you than just use foxel/seafile-docker and leave the default port on 80.

The files I used are here:

https://gist.github.com/rcludwick/adf58480fa2baf8db7861afee4c9ba78

1.  Run docker-compose up on the nginx-docker-compose.yml file in my gist.

That runs the jwilder/nginx-proxy image, jrcs/letsencrypt-docker-proxy-companion, sets up some networks, and starts nginx listening on 443 and 80.

2.  Checkout foxel/seafile-docker.

I have modified the foxel/seafile-docker to add linuxserver/ddclient (seafile-docker-compose.yml).  

Additionally, look over the seafile-docker-compose.override.yml in my gist and make changes as necessary.   This file sets up the nginx-gen and letsencrypt settings for the seafile container.

Instead of looking up the password in the mysql logs, I just set the password in the override.  Remove the password lines to use the ones generated by the docker instance.

3.  I changed seafile's nginx config with the following patch, so that we can keep port 80 clear.

```
+++ b/etc/nginx/sites-available/seafile.conf
@@ -1,6 +1,6 @@
 server {
-    listen       80;
-    server_name  "";
+    listen       8888;
+    server_name  _;
 
     location / {

```
The Dockerfile also needs to EXPOSE 8888 instead of port 80.

4.  When you're happy, run docker-compose up to get seafile running, and then follow the instructions in foxel/seafile-docker to setup seafile.

Check the logs for nginx-gen and letsencrypt images to make sure things are working well.

**Caveats**: 
The networks could be made better to limit exposure to networks, but it's kind of nice to debug things by hitting ports. 

Also if I had more time, I would have figured out how to map /seafhttp using only 1 nginx instance instead of two, but it works good enough.  :)

**Comment by Dehalion** [comment]
@rcludwick Thank you very much for all the help. Exactly what I had in mind (I'm already using nginx-proxy with letsencrypt) and was looking for a better way to run a second instance. You saved me a LOT of time here :+1:

**Comment by rcludwick** [comment]
There are a few more things to do that should be done to make life a little
better for the next person.

1.  Fix the port assignment in the override to use port 8888 (or whatever)
instead of patching the foxel/seafile-docker source.

2.  Fix the docker network connections so they're all the sane after you
test it out that it works.  (seafile should be on the proxy net, instead of
on default say)

3.  Move ddclient into it's own docker-compose.yml

With those things done, then all one needs to do is to provide two things.

1.  A ddclient config (optional).

2.  An override for seafile-docker to specify the secrets, ports, etc.

**Comment by freeplant** [comment]
Please try the latest version. `launcher` is no longer used.

**Comment by ilyaglow** [comment]
Compose version was reverted or something?

**Comment by tholu** [comment]
@freeplant Can you add a sample `docker-compose.yml`? This would help tremendously.
