### ISSUE TITLE
main : Unable to find type [CommandNotFoundException].

### ISSUE THREAD

**Issue by ulayera** [haiwen/seafile-docker#39]
I know nothing about .NET or Powershell or windows, but tried the Windows specific README and got this error:

~~~
PS C:\Users\server\seafile-docker> .\launcher.ps1 bootstrap
main : Unable to find type [CommandNotFoundException].
En C:\Users\server\seafile-docker\launcher.ps1: 602 Character: 1
+ main @args
+ ~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (CommandNotFoundException:TypeName) [main], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound,main
~~~
Actually i edited the launcher.ps1 where the CommandNotFoundException was catched, leaving just "Exception" (as a Java developer, it made sense), and it worked.

I have Windows 10 installed, these are the versions of .NET:

~~~
``PS C:\Users\server\seafile-docker> Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP' -recurse |
>> Get-ItemProperty -name Version -EA 0 |
>> Where { $_.PSChildName -match '^(?!S)\p{L}'} |
>> Select PSChildName, Version

PSChildName Version
----------- -------
Client      4.7.02556
Full        4.7.02556
Client      4.0.0.0
~~~

**Comment by mrled** [comment]
Hello,

I'm not a developer for this project and I don't have an end-user fix for this problem. However, I ran into the problem in my own code today, and found this issue with no answers.

My scenario is running Powershell 5.1 on Windows 10 Pro x64. In my case, when I was trying to `catch [CommandNotFoundException]`, it would fail with the `Unable to find type [CommandNotFoundException` error referenced above. However, after changing the catch to use the fully qualified type name of `catch [System.Management.Automation.CommandNotFoundException]`, and I was able to properly catch the exception.

If you want to test this, you could try changing [this line](https://github.com/haiwen/seafile-docker/blob/master/launcher.ps1#L195) in `launcher.ps1` to use the fully qualified type ID, as I did above.

Again, I want to stress that I'm not a developer on this project. I only want to report what worked for me since I found this error on Google but there was no answer on this page or any other in my search results. I hope it helps :) but if not, please ignore the spam.

**Comment by shoeper** [comment]
Launcher is not being used anymore.
