### ISSUE TITLE
New seafile-docker version fails to start up

### ISSUE THREAD

**Issue by moritzschaefer** [haiwen/seafile-docker#77]
Using the new way to start seafile-docker (i.e. NOT using the launcher script) fails with "502 Bad Gateway". 
After some investigation I found, that the MySQL server didn't come up so the start script waited forever. Looking at /var/log/mysql.log I saw this:

> tail: mysql.log: file truncated
> 180704  7:56:05 [Note] /usr/sbin/mysqld (mysqld 10.0.34-MariaDB-0ubuntu0.16.04.1) starting as process 5068 ...
> 180704  7:56:05 [Warning] Can't create test file /var/lib/mysql/9edab315ec8e.lower-test
> /usr/sbin/mysqld: Can't change dir to '/var/lib/mysql/' (Errcode: 13 "Permission denied")
> 180704  7:56:05 [ERROR] Aborting
> 
> 180704  7:56:05 [Note] /usr/sbin/mysqld: Shutdown complete
> 
> tail: mysql.log: file truncated
> 180704  7:56:06 [Note] /usr/sbin/mysqld (mysqld 10.0.34-MariaDB-0ubuntu0.16.04.1) starting as process 5073 ...
> 180704  7:56:06 [Warning] Can't create test file /var/lib/mysql/9edab315ec8e.lower-test
> /usr/sbin/mysqld: Can't change dir to '/var/lib/mysql/' (Errcode: 13 "Permission denied")
> 180704  7:56:06 [ERROR] Aborting
> 
> 180704  7:56:06 [Note] /usr/sbin/mysqld: Shutdown complete
> 
> tail: mysql.log: file truncated
> 180704  7:56:07 [Note] /usr/sbin/mysqld (mysqld 10.0.34-MariaDB-0ubuntu0.16.04.1) starting as process 5078 ...
> 180704  7:56:07 [Warning] Can't create test file /var/lib/mysql/9edab315ec8e.lower-test
> /usr/sbin/mysqld: Can't change dir to '/var/lib/mysql/' (Errcode: 13 "Permission denied")
> 180704  7:56:07 [ERROR] Aborting
> 
> 180704  7:56:07 [Note] /usr/sbin/mysqld: Shutdown complete

The reason was that /shared had no 'x' permission for other users (mysqld runs as 'mysql' user)

> root@9edab315ec8e:/shared# ls -lhd /var/lib/mysql
> lrwxrwxrwx 1 root root 10 Jul  4 07:38 /var/lib/mysql -> /shared/db
> root@9edab315ec8e:/shared# ls -lhd /shared/
> drwx------ 6 root root 4.0K Dec 19  2016 /shared/
> root@9edab315ec8e:/shared# chmod +x /shared
> root@9edab315ec8e:/shared# ls -lhd /shared/
> drwx--x--x 6 root root 4.0K Dec 19  2016 /shared/

fixed it...

I'm not sure if this is an issue specific to my setup or one that could occur to others..

**Comment by lorenzschmid** [comment]
Have the same problem. Adding execution rights didn't help so I just changed ownership of the folder in question

    chown -R mysql:mysql /var/lib/mysql/

**Comment by lorenzschmid** [comment]
still an issue though...

**Comment by de-conf** [comment]
Question +1
I can't start using seafile-docker in arch Linux.
This is the seafile-docker error log：
```
verifying password of user seafile ...  
Failed to connect to mysql server using user "seafile" and password "***": Access denied for user 'seafile'@'localhost' (using password: YES)

Traceback (most recent call last):
  File "/scripts/start.py", line 86, in <module>
    main()
  File "/scripts/start.py", line 56, in main
    init_seafile_server()
  File "/scripts/bootstrap.py", line 126, in init_seafile_server
    call('{} auto -n seafile'.format(setup_script), env=env)
  File "/scripts/utils/__init__.py", line 68, in call
    return subprocess.check_call(*a, **kw)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/opt/seafile/seafile-server-6.3.3/setup-seafile-mysql.sh auto -n seafile' returned non-zero exit status 255
*** /scripts/start.py exited with status 1.
*** Shutting down runit daemon (PID 24)...
*** Running /etc/my_init.post_shutdown.d/10_syslog-ng.shutdown...
Nov 30 13:47:26 9af51e2e25ec syslog-ng[17]: syslog-ng shutting down; version='3.5.6'
Nov 30 13:47:26 9af51e2e25ec syslog-ng[17]: EOF on control channel, closing connection;
*** Killing all processes...
```
Request help

**Comment by de-conf** [comment]
> 有同样的问题。添加执行权限没有帮助，所以我只是更改了相关文件夹的所有权
> 
> ```
> chown -R mysql:mysql /var/lib/mysql/
> ```

I can't start docker now, how can I change it?

**Comment by de-conf** [comment]
I found the docker in kernel4.19+ related issues, and added such kernel parameters ` GRUB_CMDLINE_LINUX="vsyscall=emulate overlay.metacopy=N"  ` the problem remains

**Comment by yadalik** [comment]
`*** Running /etc/my_init.d/01_create_data_links.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
Dec  3 13:00:45 bc0310611011 syslog-ng[20]: syslog-ng starting up; version='3.5.6'
Dec  3 13:00:46 bc0310611011 syslog-ng[20]: EOF on control channel, closing connection;
*** Running /etc/my_init.d/99_mysql_setup.sh...
Rebuilding mysql data dir
Starting mysqld
Waiting for mysqld to come online
Dec  3 13:00:46 bc0310611011 mysqld_safe: Starting mysqld daemon with databases from /var/lib/mysql
Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [Note] /usr/sbin/mysqld (mysqld 10.0.34-MariaDB-0ubuntu0.16.04.1) starting as process 192 ...
Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [Warning] Can't create test file /var/lib/mysql/bc0310611011.lower-test
Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [ERROR] mysqld: Can't create/write to file '/var/lib/mysql/aria_log_control' (Errcode: 13 "Permission denied")
Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [ERROR] mysqld: Got error 'Can't create file' when trying to use aria control file '/var/lib/mysql/aria_log_control'
Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [ERROR] Plugin 'Aria' init function returned error.
Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [ERROR] Plugin 'Aria' registration as a STORAGE ENGINE failed.
Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [Note] InnoDB: innodb_empty_free_list_algorithm has been changed to legacy because of small buffer pool size. In order to use backoff, increase buffer pool at least up to 20MB.
Dec  3 13:00:46 bc0310611011 mysqld:
Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [Note] InnoDB: Using mutexes to ref count buffer pool pages
Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [Note] InnoDB: The InnoDB memory heap is disabled
Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [Note] InnoDB: Compressed tables use zlib 1.2.8
Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [Note] InnoDB: Using Linux native AIO
Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [Note] InnoDB: Using CPU crc32 instructions
Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [Note] InnoDB: Initializing buffer pool, size = 128.0M
Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [Note] InnoDB: Completed initialization of buffer pool
Dec  3 13:00:46 bc0310611011 mysqld: 2018-12-03 13:00:46 7f464083e780  InnoDB: Operating system error number 13 in a file operation.
Dec  3 13:00:46 bc0310611011 mysqld: InnoDB: The error means mysqld does not have the access rights to
Dec  3 13:00:46 bc0310611011 mysqld: InnoDB: the directory.
Dec  3 13:00:46 bc0310611011 mysqld: 2018-12-03 13:00:46 7f464083e780  InnoDB: Operating system error number 13 in a file operation.
Dec  3 13:00:46 bc0310611011 mysqld: InnoDB: The error means mysqld does not have the access rights to
Dec  3 13:00:46 bc0310611011 mysqld: InnoDB: the directory.
Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [ERROR] InnoDB: Creating or opening ./ibdata1 failed!
Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [ERROR] InnoDB: Could not open or create the system tablespace. If you tried to add new data files to the system tablespace, and it failed here, you should now edit innodb_data_file_path in my.cnf back to what it was, and remove the new ibdata files InnoDB created in this failed attempt. InnoDB only wrote those files full of zeros, but did not yet use them in any way. But be careful: do not remove old data files which contain your precious data!
Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [ERROR] Plugin 'InnoDB' init function returned error.
Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [Note] Plugin 'FEEDBACK' is disabled.
Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [ERROR] Unknown/unsupported storage engine: InnoDB
Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [ERROR] Aborting
Dec  3 13:00:46 bc0310611011 mysqld:
Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [Note] /usr/sbin/mysqld: Shutdown complete
Dec  3 13:00:46 bc0310611011 mysqld:
Dec  3 13:00:46 bc0310611011 mysqld_safe: mysqld from pid file /var/run/mysqld/mysqld.pid ended
`

**Comment by de-conf** [comment]
> 当从安装在VMWare上的ubuntu服务器虚拟机运行命令时，我遇到这种错误，共享文件夹，安装了来自Windows 10的vmware（它安装在linux中的/ mnt / hgfs / te）。如果我运行此命令为常规，而不是挂载文件夹（例如在我的家庭linux文件夹中，如/ home / i / todel），seafile启动正常：
> 
> ```
> docker run -d --name seafile \
>   -e SEAFILE_SERVER_HOSTNAME=seafile.example.com \
>   -e SEAFILE_ADMIN_EMAIL=me@example.com \
>   -e SEAFILE_ADMIN_PASSWORD=a_very_secret_password \
>   -v /mnt/hgfs/te:/shared \
>   -p 80:80 \
>   seafileltd/seafile:latest
> ```
> 从win10安装文件夹，我得到logs \和seafile \文件夹中有文件，db \ folder为空：
> 
> ```
> *** Running /etc/my_init.d/01_create_data_links.sh...
> *** Running /etc/my_init.d/10_syslog-ng.init...
> Dec  3 13:00:45 bc0310611011 syslog-ng[20]: syslog-ng starting up; version='3.5.6'
> Dec  3 13:00:46 bc0310611011 syslog-ng[20]: EOF on control channel, closing connection;
> *** Running /etc/my_init.d/99_mysql_setup.sh...
> Rebuilding mysql data dir
> Starting mysqld
> Waiting for mysqld to come online
> Dec  3 13:00:46 bc0310611011 mysqld_safe: Starting mysqld daemon with databases from /var/lib/mysql
> Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [Note] /usr/sbin/mysqld (mysqld 10.0.34-MariaDB-0ubuntu0.16.04.1) starting as process 192 ...
> Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [Warning] Can't create test file /var/lib/mysql/bc0310611011.lower-test
> Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [ERROR] mysqld: Can't create/write to file '/var/lib/mysql/aria_log_control' (Errcode: 13 "Permission denied")
> Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [ERROR] mysqld: Got error 'Can't create file' when trying to use aria control file '/var/lib/mysql/aria_log_control'
> Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [ERROR] Plugin 'Aria' init function returned error.
> Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [ERROR] Plugin 'Aria' registration as a STORAGE ENGINE failed.
> Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [Note] InnoDB: innodb_empty_free_list_algorithm has been changed to legacy because of small buffer pool size. In order to use backoff, increase buffer pool at least up to 20MB.
> Dec  3 13:00:46 bc0310611011 mysqld:
> Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [Note] InnoDB: Using mutexes to ref count buffer pool pages
> Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [Note] InnoDB: The InnoDB memory heap is disabled
> Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
> Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
> Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [Note] InnoDB: Compressed tables use zlib 1.2.8
> Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [Note] InnoDB: Using Linux native AIO
> Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [Note] InnoDB: Using CPU crc32 instructions
> Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [Note] InnoDB: Initializing buffer pool, size = 128.0M
> Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [Note] InnoDB: Completed initialization of buffer pool
> Dec  3 13:00:46 bc0310611011 mysqld: 2018-12-03 13:00:46 7f464083e780  InnoDB: Operating system error number 13 in a file operation.
> Dec  3 13:00:46 bc0310611011 mysqld: InnoDB: The error means mysqld does not have the access rights to
> Dec  3 13:00:46 bc0310611011 mysqld: InnoDB: the directory.
> Dec  3 13:00:46 bc0310611011 mysqld: 2018-12-03 13:00:46 7f464083e780  InnoDB: Operating system error number 13 in a file operation.
> Dec  3 13:00:46 bc0310611011 mysqld: InnoDB: The error means mysqld does not have the access rights to
> Dec  3 13:00:46 bc0310611011 mysqld: InnoDB: the directory.
> Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [ERROR] InnoDB: Creating or opening ./ibdata1 failed!
> Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [ERROR] InnoDB: Could not open or create the system tablespace. If you tried to add new data files to the system tablespace, and it failed here, you should now edit innodb_data_file_path in my.cnf back to what it was, and remove the new ibdata files InnoDB created in this failed attempt. InnoDB only wrote those files full of zeros, but did not yet use them in any way. But be careful: do not remove old data files which contain your precious data!
> Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [ERROR] Plugin 'InnoDB' init function returned error.
> Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
> Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [Note] Plugin 'FEEDBACK' is disabled.
> Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
> Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [ERROR] Unknown/unsupported storage engine: InnoDB
> Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [ERROR] Aborting
> Dec  3 13:00:46 bc0310611011 mysqld:
> Dec  3 13:00:46 bc0310611011 mysqld: 181203 13:00:46 [Note] /usr/sbin/mysqld: Shutdown complete
> Dec  3 13:00:46 bc0310611011 mysqld:
> Dec  3 13:00:46 bc0310611011 mysqld_safe: mysqld from pid file /var/run/mysqld/mysqld.pid ended
> ```

This is stupid, do you understand?
The two file systems are completely inconsistent

**Comment by yadalik** [comment]
Yeah, but no, cause everything else except this mysql problem in logs seems
to work fine (even log-file, sayin that we have a problem, was created in
that folder, I can see and read text ~4kb at d:\gu\logs\var-log\error and
even some other specific log-file for mysql ~5.1kb at
d:\gu\logs\var-log\mysql\error.log, i.e. this docker command  have
succesfully  created quite a few files, some of them 0-sized, some of them
not, see also imgur screen for sizes and zip for all created files:

https://i.imgur.com/U97t0Dm.png

d:\gu\logs\var-log\error
d:\gu\logs\var-log\daemon.log
d:\gu\logs\var-log\messages
d:\gu\logs\var-log\syslog
d:\gu\logs\var-log\mysql-bootstrap.log
d:\gu\logs\var-log\fsck\checkroot
d:\gu\logs\var-log\fsck\checkfs
d:\gu\logs\var-log\dmesg
d:\gu\logs\var-log\bootstrap.log
d:\gu\logs\var-log\mysql\error.log
d:\gu\logs\var-log\lastlog
d:\gu\logs\var-log\faillog
d:\gu\logs\var-log\alternatives.log
d:\gu\logs\var-log\dpkg.log
d:\gu\logs\var-log\apt\term.log
d:\gu\logs\var-log\apt\history.log
d:\gu\logs\var-log\nginx\access.log
d:\gu\logs\var-log\nginx\error.log
d:\gu\logs\var-log\btmp
d:\gu\logs\var-log\wtmp

пн, 3 дек. 2018 г. в 17:05, 陈佳庚 <notifications@github.com>:

**Comment by KevinGage** [comment]
Same problem and fix for me.  Still an issue

**Comment by fcying** [comment]
Same problem and fix for me. Still an issue

**Comment by walkerwzy** [comment]
> Have the same problem. Adding execution rights didn't help so I just changed ownership of the folder in question
> 
> ```
> chown -R mysql:mysql /var/lib/mysql/
> ```

how to do this on windows? I use docker for windows and show a folder (e.g. e:/seafile-mysql),

**Comment by luixal** [comment]
I just found a related problem when running docker on linux (Ubuntu 18.04) and trying to use samba mounted directories. I couldn't solve the problems related to mysql, but figured out a solution for the seafile chown problem:

1. Add this options to the samba directory entry on `/etc/fstab`: ```dir_mode=0777,file_mode=0777,nounix```
2. Add user seafile to linux using: ```useradd seafile```
3. Change ownership of the mounted dir to seafile user: ```chown -R seafile:seafile /mnt/shared/seafile/```
4. Start docker compose as usual: ```docker-compose -d up```

That worked for me, although keeping mysql volume in the linux host.
